# Example Configuration for TI-Toolbox Analysis
# This file shows how to customize the analysis for different use cases

# Example 1: Quick Q3 Analysis Only
analysis:
  questions:
    - "Q3"  # Only run demographic analysis
  save_results: true
  save_plots: true
  output:
    results_dir: "../results/tables"
    figures_dir: "../results/figures"

# Example 2: Minimal Data Set
data:
  data_dir: "../data/processed"
  regions:
    - name: "Left_Insula"
      optimization_types: ["max"]  # Only max optimization
      description: "Left Insula region (max only)"
  conditions:
    - "ernie"
    - "mapped"
    - "optimized"

# Example 3: Conservative Statistical Settings
statistics:
  alpha: 0.01  # More stringent significance level
  effect_size:
    small: 0.05
    medium: 0.25
    large: 0.4
  normality_test: "shapiro"
  correlation_methods:
    - "spearman"  # Only non-parametric correlations

# Example 4: High-Quality Plotting
plotting:
  figure:
    dpi: 600  # Higher resolution
    format: "pdf"  # Vector format for publications
    style: "seaborn-v0_8-whitegrid"
  colors:
    ernie: "#1f77b4"
    mapped: "#ff7f0e"
    optimized: "#2ca02c"
  theme: "publication"

# Example 5: Development Settings
pipeline:
  run_all_regions: false
  default:
    region: "Left_Insula"
    optimization_type: "max"
  parallel:
    enabled: false
    max_workers: 1  # Single-threaded for debugging
  logging:
    level: "DEBUG"  # More verbose logging
    save_logs: true
    log_file: "debug_analysis.log"

# Example 6: Strict Validation
validation:
  quality:
    min_participants: 20  # Higher minimum
    max_missing_percentage: 10.0  # Lower tolerance
  check_files: true
  validate_format: true 