# TI-Toolbox Analysis Configuration
# This file defines all analysis parameters, regions, and settings

# Analysis Settings
analysis:
  # Which research questions to run
  questions:
    - "Q3"           # Demographic factors analysis
    - "pairwise"     # Pairwise comparisons (ernie vs mapped, ernie vs optimized, mapped vs optimized)
  
  # Whether to save results and plots
  save_results: true
  save_plots: true
  
  # Output directories (relative to analysis directory)
  output:
    results_dir: "../results/tables"
    figures_dir: "../results/figures"

# Data Settings
data:
  # Path to processed data directory (relative to case_studies directory)
  data_dir: "data/processed"
  
  # Available regions and their optimization types
  regions:
    - name: "Left_Insula"
      optimization_types: ["max", "normal"]
      description: "Left Insula region"
      
    - name: "Right_Hippocampus"
      optimization_types: ["max"]
      description: "Right Hippocampus region"
      
    - name: "sphere_x36.10_y14.14_z0.33_r5"
      optimization_types: ["max"]
      description: "Spherical target at coordinates (36.10, 14.14, 0.33) with radius 5mm"
  
  # Available conditions for comparisons
  conditions:
    - "ernie"      # Ernie condition
    - "mapped"     # Mapped condition  
    - "optimized"  # Optimized condition (also called "opt")

# Statistical Analysis Settings
statistics:
  # Significance level for statistical tests
  alpha: 0.05
  
  # Effect size thresholds
  effect_size:
    small: 0.1
    medium: 0.3
    large: 0.5
  
  # Normality test method
  normality_test: "shapiro"  # Options: "shapiro", "ks", "anderson"
  
  # Correlation methods for Q3 analysis
  correlation_methods:
    - "pearson"
    - "spearman"

# Plotting Settings
plotting:
  # Figure settings
  figure:
    dpi: 300
    format: "png"
    style: "seaborn-v0_8-whitegrid"
  
  # Color schemes
  colors:
    ernie: "#1f77b4"      # Blue
    mapped: "#ff7f0e"     # Orange
    optimized: "#2ca02c"  # Green
  
  # Plot themes
  theme: "publication"  # Options: "publication", "default"

# Analysis Pipeline Settings
pipeline:
  # Whether to run all regions automatically
  run_all_regions: true
  
  # Default region and optimization type for single runs
  default:
    region: "Left_Insula"
    optimization_type: "max"
  
  # Parallel processing settings
  parallel:
    enabled: false
    max_workers: 4
  
  # Logging settings
  logging:
    level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR"
    save_logs: true
    log_file: "analysis.log"

# Validation Settings
validation:
  # Data quality thresholds
  quality:
    min_participants: 10
    max_missing_percentage: 20.0
  
  # File existence checks
  check_files: true
  
  # Data format validation
  validate_format: true 